### ISSUE TITLE
Nothing to do here

### ISSUE THREAD

**Issue by ArthurLDM** [jzweifel/RetroTracker#1]
Hey dude =)
I'm sorry, this has nothing to do with retrotracker ! 
But I found one of your post on this page : https://www.reddit.com/r/hearthstone/comments/268fkk/simple_hearthstone_logging_see_your_complete_play/

And I would like to know if you still have the HSLogReader you wrote ? 
I would be really interested in seeing the code =) 
You con contact me at qatarthur@hotmail.com if you want =) 
Thanks dude and sorry for spaming you git :(

**Comment by jzweifel** [comment]
I don't have the GH repo anymore, but I may have the repo still cloned on another machine. I'll check and get back to you!

**Comment by ArthurLDM** [comment]
That would be soooo awsome =)

**Comment by jzweifel** [comment]
Looks like I don't have a local copy of that repository either. Sorry!
